# Generated by Django 4.2.11 on 2024-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_seller_product_total_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.ImageField(default='uploads/no_image.jpg', upload_to='uploads'),
        ),
    ]
